version: "3.9"

services:
    api:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - redis

    worker:
        build: .
        command: celery -A app.worker.celery worker --loglevel=info
        depends_on:
            - redis

    redis:
        image: redis:alpine
